// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWsb_PPR4JsiQ0LdvtrHyQa6nVdfNXQ3k',
    appId: '1:750705282247:web:74f39ff92a28cb909302e2',
    messagingSenderId: '750705282247',
    projectId: 'lorby-38481',
    authDomain: 'lorby-38481.firebaseapp.com',
    storageBucket: 'lorby-38481.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtXuzP1zLyssWzpfSeiwM0WX_fRSzMB3U',
    appId: '1:750705282247:android:6e307a2f1129a6f29302e2',
    messagingSenderId: '750705282247',
    projectId: 'lorby-38481',
    storageBucket: 'lorby-38481.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbjYt-EhWpEIQg3A6aVhq-9DdQbZM434',
    appId: '1:750705282247:ios:ac3b448b0e2600699302e2',
    messagingSenderId: '750705282247',
    projectId: 'lorby-38481',
    storageBucket: 'lorby-38481.appspot.com',
    iosBundleId: 'com.example.lorby',
  );
}
